# Generated by Django 3.2.13 on 2022-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='snsuser',
            old_name='sid',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='snsuser',
            old_name='sns',
            new_name='kakao',
        ),
    ]
