# Generated by Django 3.2.13 on 2022-05-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220508_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sns',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sns',
            name='social',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sns',
            name='uid',
            field=models.ForeignKey(db_column='uid', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
