# Generated by Django 3.2.13 on 2022-05-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220508_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snsuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='snsuser',
            name='kakao',
        ),
    ]
