# Generated by Django 3.2.13 on 2022-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220508_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=128)),
                ('social', models.CharField(default='', max_length=128)),
                ('access_token', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
