# Generated by Django 3.2.13 on 2022-05-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_socialtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='expiry',
            field=models.IntegerField(null=True),
        ),
    ]
