# Generated by Django 3.2.13 on 2022-05-08 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_socialtoken_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
